services:
  auth-db:
    container_name: auth-db
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-cache:
    container_name: auth-cache
    image: redis:7-alpine
    ports:
      - "6379:6379"
