// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type JwkKey struct {
	KID            string
	ALG            string
	PublicJWK      json.RawMessage
	Status         string
	PrivCiphertext []byte
	PrivNonce      []byte
	WrappedDEK     []byte
	KEKRef         sql.NullString
	CreatedAt      time.Time
	RotatedAt      sql.NullTime
	NotBefore      sql.NullTime
	NotAfter       sql.NullTime
}
