// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateJWK(ctx context.Context, arg CreateJWKParams) error
	GetJWK(ctx context.Context) (GetJWKRow, error)
	GetPubJWK(ctx context.Context) ([]GetPubJWKRow, error)
	UpdateJWKToRetired(ctx context.Context) error
	UpdateJWKToRetiring(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
